import { useEffect } from "react";
import { Link, useSearch } from "wouter";
import { motion } from "framer-motion";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { CheckCircle2, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Success() {
  const search = useSearch();
  const sessionId = new URLSearchParams(search).get("session_id");

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow flex items-center justify-center py-20 px-4">
        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="max-w-md w-full glass-card p-8 rounded-2xl text-center"
        >
          <div className="w-20 h-20 bg-green-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <CheckCircle2 className="w-10 h-10 text-green-500" />
          </div>
          
          <h1 className="text-3xl font-display font-bold mb-4 text-white">
            Order Confirmed!
          </h1>
          
          <p className="text-gray-300 mb-8 leading-relaxed">
            Thank you for your order. Your Cosmic Blueprint is being generated by the stars and will be emailed to you shortly.
          </p>
          
          {sessionId && (
            <p className="text-xs text-gray-500 mb-6 font-mono">
              Ref: {sessionId.slice(0, 10)}...
            </p>
          )}

          <div className="space-y-4">
            <Link href="/">
              <Button className="w-full bg-primary text-primary-foreground hover:bg-primary/90 font-semibold h-12">
                Return Home
              </Button>
            </Link>
            <p className="text-sm text-gray-500">
              Check your spam folder if you don't see the email within 15 minutes.
            </p>
          </div>
        </motion.div>
      </main>
      
      <Footer />
    </div>
  );
}
